name: Publish Library to JitPack

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and publish
      run: ./gradlew build publish
